In [5]:
import numpy as np
arr = np.arange(0,11)
print(arr)
print(arr[2:5])
print(arr[:5])
print(arr[5:])

[ 0  1  2  3  4  5  6  7  8  9 10]
[2 3 4]
[0 1 2 3 4]
[ 5  6  7  8  9 10]


In [8]:
arr[0:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [12]:
arr = np.arange(0,11)
slice_of_arr = arr[0:5]
print(arr)
print(slice_of_arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]


In [14]:
slice_of_arr[:] = 99
print(arr) # !!!!!!!!!!!!!!!!!  slice_of_arr je samo pointer na arr
print(slice_of_arr)

[99 99 99 99 99  5  6  7  8  9 10]
[99 99 99 99 99]


In [16]:
arr_copy = arr.copy()
arr_copy[:] = 100
print(arr_copy)
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]
[99 99 99 99 99  5  6  7  8  9 10]


In [46]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]], dtype=object)
# arr_2d = np.ndarray([[5,10,15],[20.25,30],[35,40,45]])
print(type(arr_2d))
print(arr_2d.shape)
print(arr_2d)
print(arr_2d[0])
print(arr_2d[1][1])
print(arr_2d[1,1]) # isto kao i iznad


<class 'numpy.ndarray'>
(3, 3)
[[5 10 15]
 [20 25 30]
 [35 40 45]]
[5 10 15]
25
25


In [50]:
arr_2d[:2,1:]


array([[10, 15],
       [25, 30]], dtype=object)

In [51]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr[arr>4] # filtriranje

array([ 5,  6,  7,  8,  9, 10])