In [1]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr / arr

<ipython-input-4-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [5]:
1 / 0

ZeroDivisionError: division by zero

In [6]:
1 / arr

<ipython-input-6-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [7]:
arr / arr

<ipython-input-7-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
arr2d.sum()

300

In [17]:
print(arr2d.shape) # (5,5) (row, column)
print(arr2d.sum(axis = 0)) # sum rows
print(arr2d.sum(axis = 1)) # sum columns

(5, 5)
[50 55 60 65 70]
[ 10  35  60  85 110]
