In [1]:
# https://numpy.org/doc/stable/contents.html

import numpy as np # konvencija da se pise 'as np'
mylist = [1,2,3]
print(type(mylist))
mynplist = np.array(mylist)
print(type(mynplist))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)
print(np.array(my_matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((2,5)) # (row,column)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(5)
# sta ona 14. 7:00

array([1., 1., 1., 1., 1.])

In [8]:
np.linspace(0,10,3) # u linearnom intervalu daj mi 3 ravnomjerno rasprostranjena broja od 0 do 10

array([ 0.,  5., 10.])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
np.random.rand(2, 1) # u rasponu [0,1)

array([[0.63110173],
       [0.47433075]])

In [48]:
np.random.randint(0, 101, (2, 3)) # od 0 do 100 int broj, vrati 2x3 komada

array([[35, 31, 86],
       [20, 20, 66]])

In [63]:
np.random.seed(42) # ako definiras seed, rand ce uvijek vracati iste rand brojeve
print(np.random.rand(2,1))
print(np.random.rand(2,1))

[[0.37454012]
 [0.95071431]]
[[0.73199394]
 [0.59865848]]


In [68]:
arr = np.arange(0, 20)
print(arr)
print(arr.reshape(5, 4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [110]:
arr = np.random.randint(0,101,5)
print(arr)
print(arr.max())
print(arr.argmax())
print(arr.dtype)
print(arr.shape)

[97 54 23 21 68]
97
0
int64
(5,)
