In [1]:
import numpy as np # konvencija da se pise 'as np'
mylist = [1,2,3]
print(type(mylist))
mynplist = np.array(mylist)
print(type(mynplist))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)
print(np.array(my_matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((2,5)) # (row,column)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(5)
# sta ona 14. 7:00

array([1., 1., 1., 1., 1.])